
SET NOCOUNT ON
DECLARE @ID INT,@SALARY INT
DECLARE EMP_SALARY CURSOR STATIC FOR SELECT EMPID,salary FROM employee3
OPEN EMP_SALARY
IF @@CURSOR_ROWS>0
BEGIN
WHILE @@FETCH_STATUS=0 BEGIN
FETCH NEXT FROM EMP_SALARY INTO @ID,@SALARY
IF @SALARY BETWEEN 4000 AND 20000
BEGIN
UPDATE employee3 SET salary = @SALARY + 5000 
WHERE empid = @ID
END

ELSE IF @SALARY BETWEEN 40000 AND 55000
BEGIN 
UPDATE employee3 SET salary = @SALARY + 7000 
WHERE empid = @ID
END

ELSE IF @SALARY BETWEEN 55000 AND 65000
BEGIN 
UPDATE employee3 SET salary = @SALARY + 5000 
WHERE empid = @ID
END

ELSE 
BEGIN 
UPDATE employee3 SET SALARY = 0
WHERE empid = @ID
END
FETCH NEXT FROM EMP_SALARY INTO @ID,@SALARY
END
END

CLOSE EMP_SALARY
DEALLOCATE EMP_SALARY

SELECT * FROM employee3