CREATE FUNCTION HUMANRESOURCES.MONTHLYSAL(@PAYRATE FLOAT)
RETURNS FLOAT
AS 
BEGIN
RETURN (@PAYRATE *8*30)
END

DECLARE @PAYRATE FLOAT
SET @PAYRATE = 
 HUMANRESOURCES.MONTHLYSAL(12.25)
PRINT @PAYRATE


CREATE FUNCTION FX_DEPARTMENT_GNAME
(@GRNAME NVARCHAR(20))
RETURNS TABLE 
AS 
RETURN(SELECT * FROM HumanResources.Department
WHERE GroupName=@GRNAME
)

SELECT*FROM FX_DEPARTMENT_GNAME('Research and Development')